version: "3.1"
services:
  db:
    image: mysql:8.1.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "online_store_database"
      MYSQL_ROOT_PASSWORD: "r00tUser"
    restart: unless-stopped
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    restart: always
