version: "3.1"
services:
  db:
    image: mysql:8.1.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "dev"
      MYSQL_ROOT_PASSWORD: "pass"
    restart: unless-stopped

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    restart: unless-stopped

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080" # http
      - "1025:1025" # smtp
    restart: unless-stopped

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: secretpassword
    command: server --console-address ":9001" /data
    restart: unless-stopped

  # Create local S3 bucket and set it to allow public downloads.
  # This is used for local development/testing only.
  # This container will only configure the bucket and then exit.
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 root secretpassword;
      /usr/bin/mc mb myminio/goldenage-uploads;
      /usr/bin/mc anonymous set download myminio/goldenage-uploads;
      exit 0;
      "

volumes:
  minio_storage: {}
