http://localhost:5000/healthz

###
# @name signup
POST http://localhost:5000/api/users/signup
Content-Type: application/json
Accept: application/json

{
  "email": "timothy@tester.com",
  "password": "Timothy@tester12345"
}

###
# @name login
POST http://localhost:5000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "email": "timothy@tester.com",
  "password": "Timothy@tester12345"
}

###
@token = {{login.response.body.token}}
@user_id = {{login.response.body.id}}

### Send password reset link - success

POST http://localhost:5000/api/password-reset/send-reset-email
Content-Type: application/json

{
    "email": "timothy@tester.com"
}

### Send password reset link - email not found

POST http://localhost:5000/api/password-reset/send-reset-email
Content-Type: application/json

{
    "email": "does.not.exist@test.example.com"
}

### Reset password - invalid token

POST http://localhost:5000/api/password-reset/set-new-password
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFhYWFhYWFhLTA2MTUtNGQwNC1hNzk1LTljNTc1NmVmNWY0YyIsImlhdCI6MTY4MTI0NTEyMywiZXhwIjoxNjgxMjQ2MjIzfQ.oh9fSC9MHyk5iX3ZuFoPsd6WXGF5laNg_ysyAULZ1ws", 
    "password": "newPassword1"
}


### Reset password - expired

POST http://localhost:5000/api/password-reset/set-new-password
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFhYWFhYWFhLTA2MTUtNGQwNC1hNzk1LTljNTc1NmVmNWY0YyIsImlhdCI6MTY4MTI0NTEyMywiZXhwIjoxNjgxMjQ2MzIzfQ.7O80aKMcONZ7ulFZgfd4tBOB3md4vDg0zG-7A8zTa-U", 
    "password": "newPassword1"
}

### Reset password - success

POST http://localhost:5000/api/password-reset/set-new-password
Content-Type: application/json

{
    "token": "{{token}}", 
    "password": "newPassword1"
}

### Reset password - fail password checks

POST http://localhost:5000/api/password-reset/set-new-password
Content-Type: application/json

{
    "token": "{{token}}", 
    "password": "newpassword"
}

### Send Friend Request
@receiver_user_id = 239aec9f-066e-4e6a-88d7-9cdccd43445b
POST http://localhost:5000/api/users/{{user_id}}/friend-requests/{{receiver_user_id}}
Accept: application/json
Authorization: Bearer {{token}}

### Get list of sent friend requests

GET http://localhost:5000/api/users/{{user_id}}/friend-requests/sent
Accept: application/json
Authorization: Bearer {{token}}

### Get list of received friend requests

GET http://localhost:5000/api/users/{{user_id}}/friend-requests/received
Accept: application/json
Authorization: Bearer {{token}}

### Deny friend request
# @prompt friend_request_id Enter friend request id
PUT http://localhost:5000/api/users/{{user_id}}/friend-requests/{{friend_request_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "status": "denied"
}

### Accept friend request
# @prompt friend_request_id Enter friend request id
PUT http://localhost:5000/api/users/{{user_id}}/friend-requests/{{friend_request_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "status": "accepted"
}

### Get list of friends

GET http://localhost:5000/api/users/{{user_id}}/friends
Accept: application/json
Authorization: Bearer {{token}}

### Unfriend a user
# @prompt friends_user_id Enter user id of friend
DELETE http://localhost:5000/api/users/{{user_id}}/friends/{{friends_user_id}}
Accept: application/json
Authorization: Bearer {{token}}

### Update user profile

PATCH http://localhost:5000/api/users/{{user_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "first_name": "Timothy",
    "last_name": "Tester"
}
