# Need to manually add .env files that have both front- and backend environment
# variables using the secret files feature in the Render dashboard for both of
# the environment groups (onlinestore-staging and onlinestore-prod)

services:
  - type: web
    name: onlinestore-backend-stg
    env: node
    region: frankfurt
    plan: free
    branch: main
    rootDir: backend
    autoDeploy: false
    numInstances: 1
    envVars:
      - fromGroup: onlinestore-staging
    buildCommand: npm ci --omit=dev
    startCommand: npm start
    healthCheckPath: /healthz

  - type: web
    name: onlinestore-frontend-stg
    env: static
    branch: main
    rootDir: frontend
    autoDeploy: false
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - fromGroup: onlinestore-staging

  - type: web
    name: onlinestore-backend-prod
    env: node
    region: frankfurt
    plan: free
    branch: production
    rootDir: backend
    autoDeploy: false
    numInstances: 1
    envVars:
      - fromGroup: onlinestore-prod
    buildCommand: npm ci --omit=dev
    startCommand: npm start
    healthCheckPath: /healthz

  - type: web
    name: onlinestore-frontend-prod
    env: static
    branch: production
    rootDir: frontend
    autoDeploy: false
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - fromGroup: onlinestore-prod
