name: Frontend Pull Request Check

on:
  pull_request:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/frontend-pr.yml
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Lint code
        working-directory: ./frontend
        run: npm run lint

      - name: Prettier check
        working-directory: ./frontend
        run: npx prettier --check .

      - name: Install DB
        uses: shogo82148/actions-setup-mysql@v1.23.0
        with:
          distribution: "mysql"
          mysql-version: "8.1"
          root-password: pass

      - name: Init DB
        working-directory: ./backend
        env:
          TEST_DATABASE_URL: "mysql://root:pass@127.0.0.1:3306/test"
        run: |
          npx -y dbmate -e TEST_DATABASE_URL --no-dump-schema up
          # insert test data
          mysql -h 127.0.0.1 -u root -ppass test < ./db/testdata/file.sql

      - name: Run tests
        working-directory: ./frontend
        run: npx vitest run --coverage

      - name: Save code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: frontend-code-coverage-report
          path: ./frontend/coverage

      - name: Upload test coverage results to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          base-path: ./frontend/coverage

  e2e-tests:
    uses: ./.github/workflows/e2e-tests.yaml
    secrets: inherit
